openapi: 3.0.0
info:
  version: 1.0.0
  title: Subscription1-Sample1 App
paths:
  /hello:
    get:
      summary: Get hello message
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
